### ISSUE TITLE
RealID for Battle.net Tag Swap

### ISSUE THREAD

**Issue by shepherdjay** [HearthSim/HSReplay.net#113]
Regarding the limitation on RealID players if there was a way for the user to specify what the battle.net tag of a real player is it seems the xml file could be parsed prior to upload to perform a swap of the RealID with that user's Battle.net tag.

This would allow better sharing and searching of replays by player name on HSReplay.net

**Comment by jleclanche** [comment]
The replays (including the db objects) actually include the `account_lo` / `account_hi` values which uniquely identify an account, so that's what we'd be using.

Can I ask what's the use case exactly here though? We've asked Blizzard if it's possible to make it so that we don't ever have to deal with player real names, as that's a privacy issue we really don't want to have to manage.

**Comment by shepherdjay** [comment]
> Can I ask what's the use case exactly here though? We've asked Blizzard if it's possible to make it so that we don't ever have to deal with player real names, as that's a privacy issue we really don't want to have to manage.

For the privacy reasons mentioned when sharing replays as well as when trying to filter the replays by player name. Currently the replays against a RealID opponent also can't be filtered either by name or battle.net tag.

**Comment by jleclanche** [comment]
There isn't much we can do about that unfortunately. The game logs don't have the information required to differenciate between a realid name and a battletag. All we know is that "if it has spaces and is a real player, it's probably a real name" but it's not always true.

**Comment by jleclanche** [comment]
I've been thinking about adding a proper "global player" object which aggregates by accountHi/accountLo, letting us track players and get their real battletags. But it's not foolproof (battletags can change) and would be a lot of work, and it wouldn't completely solve this issue.

**Comment by shepherdjay** [comment]
If as a user I had the option to specify those mappings manually for the system it could perform a field swap for at least the filtering and sharing purposes. ie. I could specify via an option somewhere that "Joe Smith" is actually "Tundra32"

Won't solve all niche cases such as two individuals sharing the same RealId name but may help in a majority.

**Comment by shepherdjay** [comment]
In fact it may be useful to add that functionality to the replay itself which could then use the accountHi and accountLo fields to map past and present games at users request

**Comment by jleclanche** [comment]
I'd rather not allow arbitrary input like that. We do want a setting to simply anonymize a replay (removing the name altogether), though it's trickier than it sounds to actually implement which is why it hasn't been done yet. A while back we discussed a design that lets us output an anonymized replay xml stream without having to perform reprocessing, so maybe when that comes up we'll look into an "anonymize" toggle again.

**Comment by jleclanche** [comment]
As of next patch, real names will no longer appear in the logs, it will always be the player name, which solves this issue.
