### ISSUE TITLE
Use ArrayField for decklists on postgresql

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#21]
https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/fields/#arrayfield
https://www.postgresql.org/docs/9.1/static/arrays.html

**Comment by amw2104** [comment]
I'm not sure I agree with this. As I would like to make sure we retain the ability to use the ORM in order to discover all the decks that include a specific card or that include a specific number of a card. I think using this field might force those queries to be done via tablescan instead of index.

**Comment by amw2104** [comment]
Determined to be not appropriate for our use case after reviewing postgres docs:

"Tip: Arrays are not sets; searching for specific array elements can be a sign of database misdesign. Consider using a separate table with a row for each item that would be an array element. This will be easier to search, and is likely to scale better for a large number of elements."
- https://www.postgresql.org/docs/9.1/static/arrays.html
