### ISSUE TITLE
Deck matchups for each class

### ISSUE THREAD

**Issue by garyking** [HearthSim/HSReplay.net#272]
I'm surprised to see no class matchups for each deck. For instance, when clicking on a deck, it should show what win percentage the deck has vs. each class.

**Comment by beheh** [comment]
I'm working on this.

Am 15.04.2017 02:29 schrieb "garyking" <notifications@github.com>:

I'm surprised to see no class matchups for each deck. For instance, when
clicking on a deck, it should show what win percentage the deck has vs.
each class.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/HearthSim/HSReplay.net/issues/272>, or mute the thread

**Comment by beheh** [comment]
This has been done in a tabular form. We might add a chart down the line.

**Comment by garyking** [comment]
The up and down arrows, what do they indicate? Change in the past X days?
