### ISSUE TITLE
[Julian] Add a way to mass-delete replays

### ISSUE THREAD

**Issue by beheh** [HearthSim/HSReplay.net#275]
Deleting replays one-by-one is very tedious. We should add a way, be it a single button in the account settings or a checkbox system on the replays page to remove multiple replays at once.

**Comment by jleclanche** [comment]
I don't know if I really want to do that. Especially since there is no way for a user to delete their statistical data (the premium bits). Replay deletes are annoying in that they desync the user with what data is actually available; they're mostly there for users who specifically want to get rid of certain games from their list (eg. they ended up being linked somewhere they didn't want it to be, or they mistakenly uploaded an innkeeper game or some such).

Since the launch, we've had 3 mass delete requests, which is just fine to handle manually as a support case.
