### ISSUE TITLE
Add Support To Deck Details Page to Handle No Global Stats

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#295]
In this state only the similar decks tab and an overview tab with the card list, the mana curve, and pie charts showing the distribution of card type, rarity, mana cost, and card set should be rendered. The winrate and popularity over time charts should be collapsed with messaging that says "Insufficient Replay Volume For Global Statistics". The current winrate data by opponent class that is on the "Overview" tab will need to be moved to a different tab that can be disabled when there is no global data.

**Comment by amw2104** [comment]
HDT Should enable the link to the website if:
A) The shortid is in the inventory
B) Their are replays that have been uploaded to the page.

**Comment by azeier** [comment]
As of https://github.com/HearthSim/HSReplay.net/commit/195b5dd40ba54fb06fab9e23109f0921caf8fd00 deck pages without data now display the cardlist on the left instead of the hero image and a "This deck does not have enough data." message instead of the charts and hide any filters.
If the page has personal data (and the user has access to those) the hero image on the left stays, to not have duplicate lists when on the "My Statistics" tab. 

Example: https://hsreplay.net/decks/PSjKdWES3EbqueVULEwdMg/

Currently missing are the manacurve and other static charts, but I think those belong into another issue as part of a "deck detail overview improvement/rework" since they apply to the data based version of deck pages as well.
