### ISSUE TITLE
Add archetype matchups on deck & archetype detail pages

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#343]

**Comment by azeier** [comment]
Implemented on both. 

Currently the displayed classes/archetypes entirely depend on the input data, so if there are no warlock matchups, warlock will be missing. That's something we'll have to look into.

Also still need to look into making the "base class winrate" clearer. Currently it can be significantly different from the individual archetype winrates (e.g. all archetypes have lower winrate than class), this is most likely due to a rather low around of opponent decks getting classified correctly.
