### ISSUE TITLE
Mechanism for identifying deck archetypes

### ISSUE THREAD

**Issue by smikula** [HearthSim/HSReplay.net#36]
There needs to be some mechanism for identifying each player's deck archetype based on the (possibly incomplete list of) cards that are in their decks.

**Comment by HandEyeProtege** [comment]
I have some ideas here and am happy to discuss.  It seems like there's two parts to the problem:

1. Come up with archetype definitions.  This could be a curated set of decklists, or, more ambitiously, it could be derived automatically via some sort of clustering algorithm.
2. For each replay that is submitted, identify the player and opponent archetypes by matching against the archetype definitions.

I've been working on #1 by prototyping a clustering algorithm that (if it turns out the way I'm hoping) should be able to dynamically group decks together into common archetypes given a big enough data set.

**Comment by jleclanche** [comment]
@smikula We've started getting some promising results with a prototype from yitef. @amw2104 can tell you some more about it.

**Comment by smikula** [comment]
Great, I'm interested to see how yitef is approaching it.  I've had good results with my prototype too.

**Comment by jleclanche** [comment]
@smikula FYI, I finished the vagrant setup this morning so it should now be much, much easier to run on windows :)

**Comment by jleclanche** [comment]
We now have archetype classification internally. Followup projects will make this public.
