### ISSUE TITLE
Card fetch failing

### ISSUE THREAD

**Issue by jrf0110** [HearthSim/HSReplay.net#609]
(index):1 Failed to load https://api.hearthstonejson.com/v1/latest/enUS/cards.json: Redirect from 'https://api.hearthstonejson.com/v1/latest/enUS/cards.json' to 'https://api.hearthstonejson.com/v1/23180/enUS/cards.json' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://hsreplay.net' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by beheh** [comment]
This is a know issue due to the user visiting HearthstoneJSON directly at some point before and the browser caching the missing Origin header, whilst S3 is not serving the Vary header. While we can't change S3's behavious, this will be fixed soon, as we intend to switch to non-CORS requests (HearthSim/npm-hearthstonejson-client#8).

**Comment by beheh** [comment]
We now have an internal ticket tracking this.
