### ISSUE TITLE
Use named URLs in the frontend

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#701]
Wherever possible, I would like to stop hardcoding URLs in the frontend. Django drives URLs very nicely. Here's an example:

```html
<li><a href="{% url 'account_api' %}">API access</a></li>
<li><a href="{% url 'oauth2_app_list' %}">OAuth apps</a></li>
{% if user.is_staff %}
	<li><a href="{% url 'account_change_password' %}">Password</a></li>
{% endif %}
<li><a href="{% url 'socialaccount_connections' %}">Connected accounts</a></li>
<li><a href="{% url 'account_delete' %}">Delete account</a></li>
```

If this were ported to react, we would lose the named URLs. I want to avoid that as we move towards react.

I'd like to suggest we start including an `urls` json dict, much like userdata, which the frontend can fetch from. That dict would be a lookup from name to url. So in the case of the snippet above it'd look something like this:

```html
<script type="application/json" id="urls">
{"account_api": "/account/api/", "socialaccount_connections": "/account/social/connections/", "account_delete": "/account/delete/"}
</script>
```

@beheh WDYT? Viable?

I don't want to tie the views to the frontend however, as I'm concerned that now both frontend and backend would need to be kept up to date whenever adding/removing urls (well, adding at least). I would rather include all core URLs on every singe page, so the whole core sitemap is available from every page. This could also even be a js file generated at compile time and available under `/static/urls.js`, cached by manifest etc; although that has the downside of no ACLs (so feature and admin urls leak; not a big deal seeing as people can just look at the source, but still nasty).

Dynamic URLs we can talk about later. I suspect it'll involve template variables in the URLs.

**Comment by beheh** [comment]
What are we trying to gain here? If the goal is to refer to a specific page in a canonical way, that's exactly what URLs by themself should already be doing (hopefully!). Compare i.e. `react-router` which simply declares URLs using an actual path:

```jsx
<Route path="/" component={HomeView} />
<Route path="/user/:name" component={UserView} />
...
<Link to="/user/benedict">Benedict</Link>
```

As you mention, including the full sitemap would lead to some unnecessary ACL work to just filter out admin stuff. The backend needs to assume which URLs the frontend can see, and we might introduce more roles in the future.

This is also not dynamic data, so we should probably just statically compile it into the bundles instead of having to do a lookup for every single URL we want to render. This leads us back to extracting Django data into our Webpack config again, which we don't want to go back to.

Once we enter dynamic URLs, there's a whole lot more to do: Template variables would lead to us doing a lot of string parsing outside of just assembling i.e.g card urls via static JS template strings, with us having to construct maybe hundreds of URLs and do repeated regexp passes as we generate some table with a lot of links.

I also don't think such a system is really worth it until we can reliably use it everywhere to safely change URLs. That would mean including API routes and stuff like Redshift queries as well, which I really would like to avoid.

Historically our URLs have been very stable. I think we can manage this until we come up with our frontend webserver solution.

**Comment by beheh** [comment]
Closing for now, an reopen if this ever becomes relevant again.
