### ISSUE TITLE
Fix High Account Claim Failure Rate - Collection Uploading

### ISSUE THREAD

**Issue by amw2104** [HearthSim/HSReplay.net#703]
![image.png](https://images.zenhubusercontent.com/57eff60a95e42b6c5ba9bd68/64d50922-cdd1-445b-afd0-4374a1619beb)

- [ ] Fix issue
- [ ] Add grafana alert to detect future regression

**Comment by jleclanche** [comment]
Graph is super misleading for the following reasons:

1. Distincts are only distinct within their time bucket. So if the time bucket is 1 minute and the user fails 60 times per hour, that's actually going to show up as 60 different datapoints. If I break down to daily count, we go down to 163 fails, 414 success. Over 3 days that's 325 fails, 1238 success. That's high but not unreasonable.
2. As the amount of existing users who have already claimed their account goes down (users are claiming their account), the ones getting the error remains fairly constant because the error does not fix itself unless users contact us.

I don't know what to do to fix this. I don't know if there's anything to fix there. If the accounts are incorrectly claimed, this fixes itself over time; if they're correctly claimed then this is a legitimate error which requires the user to either log on the correct account, or request an account merge.

**Comment by beheh** [comment]
This seems like a systematic problem that user's might experience for various reasons.

**Comment by amw2104** [comment]
Closing for now as we seem to have no easily actionable path to address this.
