### ISSUE TITLE
Socket read timeout while polling Redshift query queue

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#808]
The lambdas that poll the Redshift query refresh queue in Redis encounter periodic socket read timeouts while polling the queue. 

Not exactly sure why this happens. Notably, CloudWatch reports a trough in SortedSetQueries at the moment this error gets raised. Could also be related to establishing a lock, since `redis_lock` logs a "Getting lock..." message (but not "Got lock") right before the error is raised.

This is reported in Sentry as "TimeoutError hsreplaynet.lambdas.analytics in refresh_stale_redshift_queries" (https://sentry.io/hearthsim/hsreplaynet-lambdas/issues/553041889/)

Created as part of #133.

**Comment by beheh** [comment]
I agree that this is most likely a failure to acquire the lock. This probably has to do with the way we cron this job, where a Lambads attempt to terminate themselves after a minute, but also Lambdas are triggered every minute from outside (using a scheduled event).
I assume that this is caused by the Lambda not exitting after 60 second, because it's sleeping either actually waiting for a query to appear, or due #807.
