### ISSUE TITLE
Investigate poor test performance for HSReplay.net test suite

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#853]
As a HearthSim developer, I need to be able to run tests in the HSReplay.net suite quickly, so that I can iterate on code changes and be more productive.

Each launch of our test suite takes several minutes on a quad-core i5 machine - and that's even before our tests start running! It's likely that one or more of the following bits of test infrastructure are responsible for at least some of this latency:

- Docker Compose
- pipenv environment management
- tox environment management
- Global pytest fixtures

This story is complete when:
- [ ] We have a breakdown that shows how much each part of our test infrastructure / setup above (plus any other systems involved) contributes to the overall test cycle time
- [ ] Stories have been added to the backlog to refactor our test execution process to get the test lifecycle (for unit tests that do not require special data fixtures) down to 10 seconds or less

**Comment by beheh** [comment]
A few minutes? That seems awfully slow. While it's not perfect, this is my machine (without Docker already running):

Docker startup: ~4 seconds
Tox startup: ~8 seconds
pytest startup: ~30 seconds

Total bootstrapping: ~42 seconds
Total test time:  2.2 seconds
Total flake8 time: ~4 seconds

I don't really believe that test time (some of the tests are in the milliseconds):
![grafik](https://user-images.githubusercontent.com/929769/41072744-faf0c366-69ff-11e8-92e5-424581e6ccaf.png)

Possibly the machine is actually already running tests during my pytest bootstrapping, but buffering to my output or something.

**Comment by jleclanche** [comment]
Here are the main issues causing slowness:

1. Dependencies (tox-level): There is a bootstrap time in tox caused by downloading dependencies. Most of this is a one-time cost as both the downloads and the environment itself get cached, but it can take *ages* due to some of the larger (and completely unnecessary) dependencies we have such as the downstream ones on scipy/numpy tooling.
2. Django bootstrap time. This is by far the worst one because it not only affects tests, but *every single manage.py command*. There are several seconds spent on this. Can be worse in the case of slow IO, as a lot of this is IO-bound. This is caused by primarily the django subsystem iterating through all the installed apps, which in turn get imported, causing more imports, and so on down the chain. There are ways to optimize this, but the major rework here is to, once again, get rid of unnecessary dependencies.
3. Postgres bootstrap times. Creation of the db and running the migrations takes time. Wiping the migration will help. There are also ways to keep the database across tests, which I think is okay to enable by default.
4. load_cards takes a large amount of time (larger every patch). We can optimize it quite a bit. We can also keep the card table across tests.

**Comment by joolean** [comment]
Some questions:

- What is it exactly that tox is doing for us? Why do we need it? Why do we need tox _and_ pipenv?
- Why do we need to load cards at all in order to run tests? I did a quick scan through the test code and didn't see any obvious usage of card metadata, and certainly not at the volume at which it's being loaded.
- How many of our actual databases do we need to run the tests we have right now? Can we disable the ones that don't have any bearing on test behavior or mock out the ORM at a higher level?

**Comment by jleclanche** [comment]
> What is it exactly that tox is doing for us? Why do we need it?

Tox is our test runner runner. It runs pytest, flake8, and anything else we might throw at it. It also manages virtualenvs for each of those, and integrates really well with CI systems like travis. Think of it like `make` for python jobs. 

> Why do we need tox and pipenv?

We don't have tox *and* pipenv. Pipenv isn't used in tests because tox isn't compatible with it (yet). There's some initial ongoing work on that. If we were to use both, pipenv would be the virtualenv manager part of tox, it wouldn't affect performance directly.

> Why do we need to load cards at all in order to run tests?

We used to have tests for this part of the site, they were moved to django-hearthstone. This might be droppable.

> How many of our actual databases do we need to run the tests we have right now? Can we disable the ones that don't have any bearing on test behavior or mock out the ORM at a higher level?

I don't particularly recommend this. Creating a db is fast, it's running the migrations that isn't. And whether you do that over 1 db or 2 doesn't make a difference. Furthermore, the two dbs are just two separate connections to the same postgres instance.

**Comment by joolean** [comment]
> Tox is our test runner runner. It runs pytest, flake8, and anything else we might throw at it. It also manages virtualenvs for each of those, and integrates really well with CI systems like travis. Think of it like make for python jobs.

Right now we _only_ have pytest and flake8, so let's focus on those: Why do those two things need an orchestration layer? For example, if I want to run flake8, why can't I just run it manually? 

And why do we need a virtualenv if we're already running inside a Docker container? Surely we don't need sandboxing between pytest and flake8.

> We don't have tox and pipenv. Pipenv isn't used in tests because tox isn't compatible with it (yet). There's some initial ongoing work on that. If we were to use both, pipenv would be the virtualenv manager part of tox, it wouldn't affect performance directly.

The original command-line instructions you gave me for running tests involved running tox inside pipenv. If that's not necessary, I'll stop doing it!

**Comment by jleclanche** [comment]
> Why do those two things need an orchestration layer?

Tox is standard in the python community, and across all our projects. Furthermore, it doesn't add latency to any of this. The latency is added by creating the virtual environment. If you already have it, that is skipped. And if you don't use tox, you still need to have one.

> And why do we need a virtualenv if we're already running inside a Docker container?

First of all because the tests and the dev environment require different environments, so you can't just reuse the dev env in the docker container. Second, you don't *have* to run the tests in the docker environment, it's just more standard.

> The original command-line instructions you gave me for running tests involved running tox inside pipenv.

That part shouldn't be adding latency either. I agree that between tox and pipenv there's one layer too many. We should standardize that, but I suspect it will not help the speed issues.

**Comment by joolean** [comment]
> First of all because the tests and the dev environment require different environments, so you can't just reuse the dev env in the docker container.

Why is this? From what I can see, the test "environment" is just a few additional testing libraries, not different versions / different implementations of the web module dependencies. Is there a way to supply the test dependencies more directly?

**Comment by jleclanche** [comment]
For one thing, tox allows us to test using different library and even python versions. In other projects for example, we test on py36-django20 and py36-djangomaster. We should start doing that on hsreplaynet as well... the only reason we don't, is because our lack of tests meant it didn't give us any benefit.

**Comment by joolean** [comment]
Okay, I spent some time measuring execution times, and my data is a bit different from Benedict's. I was studying the behavior of this command: `docker-compose run django pipenv run tox [tests/mytest.py]`, although I ended up having to play around with its structure to measure it. Here are my numbers:

Docker Compose environment bootstrap: ~12 seconds
tox startup: ~4 seconds
pytest "startup" (I'll explain the quotes): Consistently at least 20s, sometimes as long as 1m50s!
pytest-django db fixture overhead, once per test session: ~3s per database, over three databases (`test_hsreplaynet`, `test_uploads`, `test_hsredshift`)

I believe the two things that are happening in that pytest startup block are actually:
- Django database migrations (which can take more than a minute)
- Our Django `load_cards` command, which runs every single session and takes ~20s regardless of whether or not cards are already loaded

The three biggest culprits above by duration are Docker Compose, migrations, and card loading. But I think the real problem I was having was failing to leverage the performance benefits of a persistent test environment. (For example, depending on the behavior of Docker Compose and tox, I think I was sometimes running migrations for every test session, which was totally unnecessary - but also not obvious to me at first.) To address this, I propose we do the following:

- Document a process for creating a persistent test environment, including running migrations
- Get rid of the `load_cards` pytest-django fixture and just run it from the command line
- Stop using tox for local testing - it can stay (if necessary) as part of the Jenkins CI/CD workflow
- Get rid of the `test_hsredshift` database (it's not used in any tests)

By makign the changes above, I've worked out a process (which involves a few small changes that I'll push to a branch tomorrow) that gets my test bootstrap time from - in some cases - almost 2 minutes, down to ~6s. This is what it's like:

Do once:

```
~/src/hearthsim$ docker-compose up -d
Creating network "hearthsim_default" with the default driver
Creating hearthsim_db_1 ... done
Creating hearthsim_redis_1 ... done
Creating hearthsim_frontend_1 ... done
Creating hearthsim_stripe_1 ... done
Creating hearthsim_django_1 ... done
~/src/hearthsim$ docker-compose exec django bash
root@62caf0e831cb:/opt/hsreplay.net/source# pipenv install -d
Installing dependencies from Pipfile.lock (748f01)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 112/112 — 00:00:09
root@62caf0e831cb:/opt/hsreplay.net/source# createdb test_hsreplaynet -Upostgres
root@62caf0e831cb:/opt/hsreplay.net/source# createdb test_uploads -Upostgres
root@62caf0e831cb:/opt/hsreplay.net/source# pipenv run python manage.py migrate --settings tests.settings
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  ...
root@62caf0e831cb:/opt/hsreplay.net/source# pipenv run python manage.py load_cards --settings tests.settings
4732 cards available
0 known cards
4732 new cards
```

Do many times:

```
~/src/hearthsim$ docker-compose exec django pipenv run pytest --ignore node_modules --reuse-db --ds=tests.settings
```

**Comment by jleclanche** [comment]
`docker-compose exec` instead of `docker-compose run` will avoid most of that docker bootstrap time you're encountering. This applies to every command you run.

> Get rid of the test_hsredshift database (it's not used in any tests)

I mean, we *can* get rid of it, but ideally we'll want it back at some point... hsreplay.net depends on it, and we should have tests for those code paths.

**Comment by joolean** [comment]
Does it actually depend on it directly?
