### ISSUE TITLE
Paladin deck classified as Zoo Warlock

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#856]
This Paladin deck was somehow classified as a Zoo Warlock deck: https://hsreplay.net/decks/FiphOJJ1JcjrBPQ1H1WkSb/

Also this customer sees a Mill Druid classified as a Warlock deck.
https://app.intercom.io/a/apps/lhrr2hfa/inbox/inbox/1790397/conversations/17984949133

As a user, I would expect there to be some kind of invariant guarantee that a suggested archetype matches the input deck's player class.

**Comment by amw2104** [comment]
The outcome of this ticket is that:
- [ ] This cannot happen again
- [ ] The known instances have been fixed.

If we haven't solved this within a week, then let's regroup to figure out where we are.

**Comment by beheh** [comment]
The root causes are fixed and the known instances corrected. I will follow up regarding no longer classifying and loading partial replays into Redshift.

**Comment by beheh** [comment]
Looks like we've had another case: https://app.intercom.io/a/apps/lhrr2hfa/inbox/inbox/all/conversations/18189889182

Checking how that could happen.

**Comment by beheh** [comment]
I think the root cause is because deck_summary_stats might still spuriously return the wrong player class if the majority (e.g. a single game) was captured with the wrong hero. It seems like some downstream queries such as `list_decks_by_win_rate` will then group by `player_class` and run into a condition where the query returns multiple rows for the same deck, which leads to the "last" row winning by overwriting the previous results. Deploying a fix to `list_decks_by_win_rate now`, and `list_decks_by_opponent_win_rate` later.
