### ISSUE TITLE
Use fswatch in vagrant to watch for css changes

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HSReplay.net#89]
https://fgimian.github.io/blog/2016/04/03/building-web-assets-using-shell-scripts/

**Comment by jleclanche** [comment]
Welp, I have a commit that fixes it, unfortunately because of the way synced folders work the even triggers *all the time*.

I'm leaving it branched. I think we'll end up using django-sass-processor.

**Comment by beheh** [comment]
Well, we could switch to [RSyncing](https://www.vagrantup.com/docs/synced-folders/rsync.html) the shared folder ([source](https://github.com/codeskyblue/fswatch/issues/3)) instead of the default VirtualBox shared folders. Otherwise we could always use a script using e.g. [chokidar](https://github.com/paulmillr/chokidar) that supports polling.

**Comment by jleclanche** [comment]
rsync is one-time and one-way, it's useless.

We'll switch to django-sass-processor. It's cleaner. I've been experimenting with it already. This is low priority anyway.

**Comment by beheh** [comment]
I agree, I'd rather have a different system than relying on rsync. For reference I know the docs say rsync is one-time, but it actually mentions [vagrant rsync-auto](https://www.vagrantup.com/docs/cli/rsync-auto.html) a few lines below.

Not sure I like relying on a django/python tool though, I'd much rather have a general solution we can also apply to Webpack. I seem to remember they wanted to remove watch at some point, but can't find the issue right now.

**Comment by jleclanche** [comment]
If we use webpack for css we can rely on webpack to handle css changes instead.
