### ISSUE TITLE
Initial ad placement on HSReplay.net

### ISSUE THREAD

**Issue by joolean** [HearthSim/HSReplay.net#905]
As a financial stakeholder in HSReplay.net, I would like to experiment with displaying a single ad on one of the pages on the site, so that I can gather some initial data about the performance of ads and user response to them. 

Before this story can be staffed, we need to know:
- How the JavaScript integration with our ad network is initialized (e.g., <script></script> drop-in) 
- What structural elements are necessary to define an ad placement (e.g., what the divs need to look like)
- An initial list of locations on the site where ads could / should appear; this list of locations will include ads inlined in the decks / cards list
  - This list will include high-priority locations (that must be tested before the story is complete) and speculative locations that do not need to be tested

This story is complete when:
- [x] The premium page / modals have been updated to add "No Ads" as a benefit of a premium subscription 
- [x] We've created the structural elements for ad placement across all of the locations identified above
- [x] We've enabled the display of a single ad unit from our ad network in one of the locations identified above and all high-priority locations have been tested for rendering with an actual ad unit from the network
- [x] The ad is not visible to premium users
- [x] There is test coverage to assert that premium users do not see ads
- [x] There's a behavior we can toggle with a feature tag that replaces a wrapped ad unit with a fake internal ad image that we can use for visual review

**Comment by amw2104** [comment]
The credentials to the Ad Network dashboard are in 1Password in the Misc Admin Vault

**Comment by amw2104** [comment]
It's fine if the Footer Ad IDs have the same ID on every page. If we have extra time as a bonus we can figure out a way to add unique IDs to the footer ads so that we can control the footer ads on specific pages.

**Comment by azeier** [comment]
Additional completion criteria:
- [ ] We have way of toggling single ad panel on and off via e.g. the admin interface.

My suggested implementation for this is the following:
- We create a table to keep track of [ad-id, enabled]
- Django packs the list of enabled ads as a json blob (array) into the header
- The frontend has a new helper class similar to `UserData`
- When loading a AdUnit with id X, the helper class is checked whether id X is enabled. If not, the unit is not rendered.

**Comment by azeier** [comment]
Ad unit placement is complete. Remaining work:
- [ ] Add fallback image for HSReplay.net Premium
- [ ] Add test to ensure premium users don't see adsall
- [ ] Merge branch, to be available behind a feature tag

**Comment by azeier** [comment]
Currently there's a bug with the measuring step in the AdContainer. When loading a page where an inactive tab contains an AdContainer, switching to the tab will cause the ads to still be hidden. This is likely due to there not always being a second render trigger after measuring, but I'm unsure how to best fix that at this time.

**Comment by azeier** [comment]
For the sake of not scope creeping too much I will consider this complete. 

Followups to this ticket are: #928 and #929

**Comment by XanGit** [comment]
I really don't know how you have implemented the ads, however it looks like you have opened a REALLY huge gate for Malvertising - and I don't think that was your intention.

Because the distribution of malware from advertising networks is the main vector for infection with trojans, ransonware and other ugly things I'm quiet paranoid with my browsing behaviour and therefor installed an addon called uMatrix.

With uMatrix active usually third-party cookies, scriptsm XHR and so on are blocked and the user allows those which she needs. So I have unblocked the scripts from api.hearthstonejson.com which are used in your site.

For the advertisment there seems to be one single script which comes from a third party site: https://s.nitropay.com/ads-86.js (in this case). Easy enough.

HOWEVER this single scripts loads several hundret other scripts, cookies, XHR, frames, tracking pixels and so on from well known malvertising networks - and I'm not sure that this is your intention. 

I have added some screenshot which shows this behaviour, if you want to try it yourself you can find the addon uMatrix at https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf for Chrome browser

Thanks for reading.


**Step 1: blocked scripts**
![ads-01](https://user-images.githubusercontent.com/15522731/43762756-189d0f4c-9a29-11e8-824e-5b5bf01b6055.png)

**Step 2: allow script to load, this is the result**
![ads-02](https://user-images.githubusercontent.com/15522731/43762765-1e72b66a-9a29-11e8-85ff-8d4d9760446a.png)
